### ISSUE TITLE
Fails to render a gif

### ISSUE THREAD

**Issue by Yajo** [flathub/com.uploadedlobster.peek#19]
After one of the recent updates, Peek can no longer render gifs.

I started a session and it exits with code 134 after trying to render a gif of ~3s:

<pre>➤ <b>flatpak</b> <font color="#06989A">run</font> <font color="#06989A">com.uploadedlobster.peek</font>
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">08:47:38.976</font>: Failed to load module &quot;pk-gtk-module&quot;
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">08:47:38.980</font>: Failed to load module &quot;pk-gtk-module&quot;
Using screen recorder backend gnome-shell
Recording to file /home/yajo/.var/app/com.uploadedlobster.peek/cache/peek/peekUOX27Z.webm
free(): double free detected in tcache 2
</pre>

Installed package details:

<pre>➤ <b>env</b> <font color="#06989A">LANG=C</font> <font color="#06989A">flatpak</font> <font color="#06989A">info</font> <font color="#06989A">com.uploadedlobster.peek</font>

Peek - Simple screen recorder with an easy to use interface

<b>          ID:</b> com.uploadedlobster.peek
<b>         Ref:</b> app/com.uploadedlobster.peek/x86_64/stable
<b>        Arch:</b> x86_64
<b>      Branch:</b> stable
<b>     Version:</b> 1.3.1
<b>     License:</b> GPL-3.0+
<b>      Origin:</b> flathub
<b>  Collection:</b> org.flathub.Stable
<b>Installation:</b> system
<b>   Installed:</b> 5,5?MB
<b>     Runtime:</b> org.gnome.Platform/x86_64/3.32
<b>         Sdk:</b> org.gnome.Sdk/x86_64/3.32

<b>      Commit:</b> 0bc623088ed136cf8b0ab0951e39d67e3153a901647268b7c8b5b17caeae7d86
<b>      Parent:</b> 9885d4b522a05fec8ffb3641cf9ae66adab6bfd053804b68becbe8cf0ae7eefd
<b>     Subject:</b> add OARS patch (e37e4488)
<b>        Date:</b> 2019-08-26 13:33:19 +0000
</pre>

**Comment by FastOSlinux** [comment]
same here

**Comment by phw** [comment]
This will be fixed by the update to 1.4

**Comment by phw** [comment]
Fixed by https://github.com/flathub/com.uploadedlobster.peek/pull/20

Release is currently building, update via Flatpak should be available soon.
