### ISSUE TITLE
Erro recording MP4

### ISSUE THREAD

**Issue by FastOSlinux** [flathub/com.uploadedlobster.peek#22]
$ flatpak info com.uploadedlobster.peek

Peek - Simples gravador de tela com uma interface fácil de usar

        ID: com.uploadedlobster.peek
       Ref: app/com.uploadedlobster.peek/x86_64/stable
      Arq.: x86_64
      Ramo: stable
    Versão: 1.4.0
   Licença: GPL-3.0+
    Origem: flathub
   Coleção: org.flathub.Stable
Instalação: system
 Instalado: 6,6 MB
error when recording in mp4
  
 Runtime: org.gnome.Platform/x86_64/3.32
       Sdk: org.gnome.Sdk/x86_64/3.32

    Commit: 930baf644d20ef919a5be76e48399f6c76ae6bb368708d1aebdedd9c9504c90f
       Pai: 0bc623088ed136cf8b0ab0951e39d67e3153a901647268b7c8b5b17caeae7d86
   Assunto: Release 1.4.0 (#20) (ffb5561c)
      Data: 2019-09-25 05:59:25 +0000

**Comment by phw** [comment]
You haven't given any details on the actual issue, but the most likely reason is that you are missing the necessary codecs on your system. MP4 recording requires the gstreamee ugly plugins being installed, please see the FAQ at https://github.com/phw/peek/blob/master/README.md#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors

Alternatively you might want to run Peek with the ffmpeg Backend:

    flatpak run com.uploadedlobster.peek -b ffmpeg

This only works if you are not using Wayland.

**Comment by FastOSlinux** [comment]
> You haven't given any details on the actual issue, but the most likely reason is that you are missing the necessary codecs on your system. MP4 recording requires the gstreamee ugly plugins being installed, please see the FAQ at https://github.com/phw/peek/blob/master/README.md#what-is-the-cause-for-could-not-start-gnome-shell-recorder-errors
> 
> Alternatively you might want to run Peek with the ffmpeg Backend:
> 
> ```
> flatpak run com.uploadedlobster.peek -b ffmpeg
> ```
> 
> This only works if you are not using Wayland.

with this command it works
