### ISSUE TITLE
Should have filesystem access to entire home folder

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/com.uploadedlobster.peek#3]
I was confused when trying to save screen recordings in ~, but they did not appear in Nautilus. Also, the desktop portal only showed the  xdg-pictures, xdg-videos and xdg-desktop folders. I assume there are quite a few use cases where people would want to store their recording elsewhere.

**Comment by phw** [comment]
This will happen with the next release of Peek (coming soon).

**Comment by phw** [comment]
Fixed in latest release
